=== vmalonso/MMP/mmp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  MMP Schema Definition
  
  Blue Blink One
  https://blueblinkone.com
  
  This schema is public and free to use.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- ================================================== -->
  <!-- Simple Types & Restrictions                        -->
  <!-- ================================================== -->

  <xs:simpleType name="BinaryFlag">
    <xs:restriction base="xs:integer">
      <xs:enumeration value="0"/>
      <xs:enumeration value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HexColorType">
    <xs:restriction base="xs:string">
      <xs:pattern value="(#[a-fA-F0-9]{6}|[a-fA-F0-9]{6})"/> <!-- Hexadecimal color (with or without #) -->
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="LineWidthType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="10"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="AreaTransparencyType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="10"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="OpacityType">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="0.0"/>
      <xs:maxInclusive value="1.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="LatitudeType">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="-90.0"/>
      <xs:maxInclusive value="90.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="LongitudeType">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="-180.0"/>
      <xs:maxInclusive value="180.0"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- ================================================== -->
  <!-- Complex Types                                      -->
  <!-- ================================================== -->

  <!-- PICTURE Structure -->
  <xs:complexType name="PictureType">
    <!-- xs:all allows fields in any order -->
    <xs:all>
      <xs:element name="DATE" type="xs:string" minOccurs="0"/> <!-- ISO 8601 -->
      <xs:element name="PICTUREURL" type="xs:string"/>
      <xs:element name="PICTURETHUMBNAILURL" type="xs:string" minOccurs="0"/>
      <xs:element name="SHOWPICTINREPORT" type="BinaryFlag" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="PicturesContainerType">
    <!-- Lists must use xs:sequence -->
    <xs:sequence>
      <xs:element name="PICTURE" type="PictureType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- GRID Structure -->
  <xs:complexType name="GridType">
    <xs:all>
      <xs:element name="CELLWIDTH" type="xs:float"/>
      <xs:element name="CELLHEIGHT" type="xs:float"/>
      <xs:element name="BEARING" type="xs:float"/>
      <xs:element name="REFLATITUDE" type="LatitudeType"/>
      <xs:element name="REFLONGITUDE" type="LongitudeType"/>
      <xs:element name="SHOWGRID" type="BinaryFlag"/>
    </xs:all>
  </xs:complexType>

  <!-- POINT Structure -->
  <xs:complexType name="PointDescType">
    <xs:all>
      <xs:element name="SHOWDESC" type="BinaryFlag" minOccurs="0"/>
      <xs:element name="SHOWLABELBACKGROUND" type="BinaryFlag" minOccurs="0"/>
      <xs:element name="SHOWDESCINREPORT" type="BinaryFlag" minOccurs="0"/>
      <xs:element name="DESC" type="xs:string" minOccurs="0"/>
      <xs:element name="DESCLAT" type="LatitudeType"  minOccurs="0"/>
      <xs:element name="DESCLONG" type="LongitudeType" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="PointType">
    <xs:all>
      <xs:element name="LAT" type="LatitudeType"/>
      <xs:element name="LONG" type="LongitudeType"/>
      <xs:element name="ALT" type="xs:float" minOccurs="0"/>
      <xs:element name="DESCPOINT" type="PointDescType" minOccurs="0"/>
      <xs:element name="PICTURES" type="PicturesContainerType" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <!-- GROUP Structure -->
  <xs:complexType name="GroupType">
    <xs:all>
      <xs:element name="ID" type="xs:string"/>
      <xs:element name="NAME" type="xs:string"/>
      <xs:element name="DESCRIPTION" type="xs:string"/>
      <xs:element name="GROUPCOLOR">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="7"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="GROUPCUSTOMCOLOR" type="HexColorType" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <!-- POLYGON Structure -->
  <xs:complexType name="PolygonType">
    <!-- Properties in any order -->
    <xs:all>
      <xs:element name="GROUPID" type="xs:string" minOccurs="0"/>
      <xs:element name="NAME" type="xs:string"/>
      <xs:element name="DESCRIPTION" type="xs:string" minOccurs="0"/>
      <xs:element name="ISHOLE" type="BinaryFlag"/>
      <xs:element name="BLOCKED" type="BinaryFlag"/>
      <xs:element name="SHAPE" default="0">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:enumeration value="0"/>  <!-- 0: No shape. It's an ordinary polygon. (Default)-->
            <xs:enumeration value="1"/> <!-- 1: circle -->
            <xs:enumeration value="2"/> <!-- 2: rectangle -->
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="NOSURFACE" type="BinaryFlag"/>
      <xs:element name="SHOWPINS" type="BinaryFlag"/>
      <xs:element name="SHOWDISTANCES" type="BinaryFlag"/>
      <xs:element name="LINECOLOR">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="6"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="LINECUSTOMCOLOR" type="HexColorType" minOccurs="0"/>
      <xs:element name="LINEWIDTH" type="LineWidthType"/>
      <xs:element name="LINESTYLE">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="4"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="AREACOLOR">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="6"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="AREACUSTOMCOLOR" type="HexColorType" minOccurs="0"/>
      <xs:element name="AREATRANSPARENCY" type="AreaTransparencyType"/>
      <xs:element name="SHOWNAME" type="BinaryFlag"/>
      <xs:element name="SHOWLABELBACKGROUND" type="BinaryFlag"/>
      <xs:element name="SHOWAREAMEASURE" type="BinaryFlag"/>
      <xs:element name="SHOWPERIMETERMEASURE" type="BinaryFlag"/>
      
      <xs:element name="COORDINATEPOLYGONLABELLATITUDE" type="LatitudeType"/>
      <xs:element name="COORDINATEPOLYGONLABELLONGITUDE" type="LongitudeType"/>  
      <xs:element name="COORDINATEPERIMETERLABELLATITUDE" type="LatitudeType"/>    
      <xs:element name="COORDINATEPERIMETERLABELLONGITUDE" type="LongitudeType"/>      
      <xs:element name="COORDINATEAREALABELLATITUDE" type="LatitudeType"/>
      <xs:element name="COORDINATEAREALABELLONGITUDE" type="LongitudeType"/>

      <xs:element name="GRID" type="GridType" minOccurs="0"/>
      <xs:element name="PICTURES" type="PicturesContainerType" minOccurs="0"/>
      
      <!-- Container for the list of points -->
      <xs:element name="POINTS" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="POINT" type="PointType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <!-- SPOT Structure -->
  <xs:complexType name="SpotDescType">
    <xs:all>
      <xs:element name="SHOWDESC" type="BinaryFlag" minOccurs="0"/>
      <xs:element name="SHOWDESCINREPORT" type="BinaryFlag" minOccurs="0"/>
      <xs:element name="DESC" type="xs:string" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="SpotType">
    <xs:all>
      <xs:element name="GROUPID" type="xs:string" minOccurs="0"/>
      <xs:element name="NAME" type="xs:string"/>
      <xs:element name="SHOWNAME" type="BinaryFlag"/>
      <xs:element name="SHOWLABELBACKGROUND" type="BinaryFlag"/>
      <xs:element name="ICON" type="xs:integer"/>
      <xs:element name="SPOTICONCOLOR">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="7"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="SPOTICONCUSTOMCOLOR" type="HexColorType" minOccurs="0"/>
      <xs:element name="LAT" type="LatitudeType"/>
      <xs:element name="LONG" type="LongitudeType"/>
      <xs:element name="ALT" type="xs:float" minOccurs="0"/>      
      <xs:element name="PICTURES" type="PicturesContainerType" minOccurs="0"/>
      <xs:element name="COORDINATESPOTNAMELATITUDE" type="LatitudeType"/>
      <xs:element name="COORDINATESPOTNAMELONGITUDE" type="LongitudeType"/>  
      <xs:element name="DESCSPOT" type="SpotDescType" minOccurs="0"/>    
    </xs:all>
  </xs:complexType>

  <!-- IMAGELAYER Structure -->
  <xs:complexType name="ImageLayerType">
    <xs:all>
      <xs:element name="NAME" type="xs:string"/>
      <xs:element name="IMAGEURL" type="xs:string" minOccurs="0"/>
      <xs:element name="OPACITY" type="OpacityType"/>
      <xs:element name="LAT1" type="LatitudeType"/>
      <xs:element name="LONG1" type="LongitudeType"/>
      <xs:element name="LAT2" type="LatitudeType"/>
      <xs:element name="LONG2" type="LongitudeType"/>
    </xs:all>
  </xs:complexType>

  <!-- ================================================== -->
  <!-- Main Definition                                    -->
  <!-- ================================================== -->

  <xs:element name="POLYGONS">
    <xs:complexType>
      <!-- Root uses xs:sequence to maintain the order of lists -->
      <xs:sequence>

        <xs:element name="POLYGON" type="PolygonType" minOccurs="0" maxOccurs="unbounded"/>
        
        <xs:element name="SPOT" type="SpotType" minOccurs="0" maxOccurs="unbounded"/>
        
        <xs:element name="IMAGELAYER" type="ImageLayerType" minOccurs="0" maxOccurs="unbounded"/>

        <xs:element name="GROUPS" minOccurs="0">
           <xs:complexType>
            <xs:sequence>
              <xs:element name="GROUP" type="GroupType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>

      <!-- Optional Root Attributes -->
      <xs:attribute name="creator" type="xs:string" use="optional"/>
      <xs:attribute name="date" type="xs:string" use="optional"/>
      <xs:attribute name="project" type="xs:string" use="optional"/>
      
    </xs:complexType>
  </xs:element>

</xs:schema>

=== vmalonso/MMP/yyyyy.xml
<?xml version="1.0" encoding="UTF-8"?>
<POLYGONS
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="mmp.xsd" creator="Measure Map Online" date="Wednesday, Jan 22, 2025 12:11 am" project="yyyyy">
	<POLYGON>
		<NAME>Hole 1</NAME>
		<DESCRIPTION/>
		<ISHOLE>1</ISHOLE>
		<BLOCKED>1</BLOCKED>
		<SHAPE>0</SHAPE>
		<NOSURFACE>0</NOSURFACE>
		<SHOWPINS>0</SHOWPINS>
		<SHOWDISTANCES>1</SHOWDISTANCES>
		<LINECOLOR>6</LINECOLOR>
		<LINECUSTOMCOLOR>ff0000</LINECUSTOMCOLOR>
		<LINEWIDTH>2</LINEWIDTH>
		<LINESTYLE>2</LINESTYLE>
		<AREACOLOR>6</AREACOLOR>
		<AREACUSTOMCOLOR>00ff00</AREACUSTOMCOLOR>
		<AREATRANSPARENCY>7</AREATRANSPARENCY>
		<SHOWNAME>0</SHOWNAME>
		<SHOWLABELBACKGROUND>1</SHOWLABELBACKGROUND>
		<SHOWAREAMEASURE>0</SHOWAREAMEASURE>
		<SHOWPERIMETERMEASURE>0</SHOWPERIMETERMEASURE>
		<COORDINATEPOLYGONLABELLATITUDE>39.98203201420783</COORDINATEPOLYGONLABELLATITUDE>
		<COORDINATEPOLYGONLABELLONGITUDE>-0.024453356047345637</COORDINATEPOLYGONLABELLONGITUDE>
		<COORDINATEPERIMETERLABELLATITUDE>39.98203201420783</COORDINATEPERIMETERLABELLATITUDE>
		<COORDINATEPERIMETERLABELLONGITUDE>-0.024453356047345637</COORDINATEPERIMETERLABELLONGITUDE>
		<COORDINATEAREALABELLATITUDE>39.98203201420783</COORDINATEAREALABELLATITUDE>
		<COORDINATEAREALABELLONGITUDE>-0.024453356047345637</COORDINATEAREALABELLONGITUDE>
		<POINTS>
			<POINT>
				<LAT>39.98201624867061</LAT>
				<LONG>-0.024657645502342482</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>0</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>0</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.98201624867061</DESCLAT>
					<DESCLONG>-0.024657645502342482</DESCLONG>
				</DESCPOINT>
			</POINT>
			<POINT>
				<LAT>39.98234058154104</LAT>
				<LONG>-0.02450479586627675</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>0</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>0</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.98234058154104</DESCLAT>
					<DESCLONG>-0.02450479586627675</DESCLONG>
				</DESCPOINT>
			</POINT>
			<POINT>
				<LAT>39.98202300562112</LAT>
				<LONG>-0.02424906659234879</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>0</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>0</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.98202300562112</DESCLAT>
					<DESCLONG>-0.02424906659234879</DESCLONG>
				</DESCPOINT>
			</POINT>
			<POINT>
				<LAT>39.981723446874625</LAT>
				<LONG>-0.024604735997437496</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>0</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>0</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.981723446874625</DESCLAT>
					<DESCLONG>-0.024604735997437496</DESCLONG>
				</DESCPOINT>
			</POINT>
			<POINT>
				<LAT>39.98201624867061</LAT>
				<LONG>-0.024657645502342482</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>0</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>0</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.98201624867061</DESCLAT>
					<DESCLONG>-0.024657645502342482</DESCLONG>
				</DESCPOINT>
			</POINT>
		</POINTS>
	</POLYGON>
	<POLYGON>
		<NAME>Polygon 1</NAME>
		<DESCRIPTION/>
		<ISHOLE>0</ISHOLE>
		<BLOCKED>1</BLOCKED>
		<SHAPE>0</SHAPE>
		<NOSURFACE>0</NOSURFACE>
		<SHOWPINS>1</SHOWPINS>
		<SHOWDISTANCES>1</SHOWDISTANCES>
		<LINECOLOR>6</LINECOLOR>
		<LINECUSTOMCOLOR>ff0000</LINECUSTOMCOLOR>
		<LINEWIDTH>2</LINEWIDTH>
		<LINESTYLE>0</LINESTYLE>
		<AREACOLOR>6</AREACOLOR>
		<AREACUSTOMCOLOR>0000ff</AREACUSTOMCOLOR>
		<AREATRANSPARENCY>7</AREATRANSPARENCY>
		<SHOWNAME>1</SHOWNAME>
		<SHOWLABELBACKGROUND>1</SHOWLABELBACKGROUND>
		<SHOWAREAMEASURE>1</SHOWAREAMEASURE>
		<SHOWPERIMETERMEASURE>0</SHOWPERIMETERMEASURE>
		<COORDINATEPOLYGONLABELLATITUDE>39.982331561306935</COORDINATEPOLYGONLABELLATITUDE>
		<COORDINATEPOLYGONLABELLONGITUDE>-0.025147058423044398</COORDINATEPOLYGONLABELLONGITUDE>
		<COORDINATEPERIMETERLABELLATITUDE>39.982331561306935</COORDINATEPERIMETERLABELLATITUDE>
		<COORDINATEPERIMETERLABELLONGITUDE>-0.025147058423044398</COORDINATEPERIMETERLABELLONGITUDE>
		<COORDINATEAREALABELLATITUDE>39.982331561306935</COORDINATEAREALABELLATITUDE>
		<COORDINATEAREALABELLONGITUDE>-0.025147058423044398</COORDINATEAREALABELLONGITUDE>
		<POINTS>
			<POINT>
				<LAT>39.98178899057892</LAT>
				<LONG>-0.026727765250370586</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>0</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>0</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.98178899057892</DESCLAT>
					<DESCLONG>-0.026727765250370586</DESCLONG>
				</DESCPOINT>
			</POINT>
			<POINT>
				<LAT>39.98333450470147</LAT>
				<LONG>-0.024338823657103638</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>0</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>0</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.98333450470147</DESCLAT>
					<DESCLONG>-0.024338823657103638</DESCLONG>
				</DESCPOINT>
				<PICTURES>
					<PICTURE>
						<PICTUREURL>https://firebasestorage.googleapis.com/v0/b/api-project-196280979389.appspot.com/o/images%2FD1d5RjEy5oWn7njdqm3CHOsWyuX2%2F20240326-06_27--NtvnOpmvi5u9tVnaDV8.png?alt=media&amp;token=30b7a64d-0c33-44a1-a8a1-406f0ef3c007</PICTUREURL>
					</PICTURE>
					<PICTURE>
						<PICTUREURL>https://firebasestorage.googleapis.com/v0/b/api-project-196280979389.appspot.com/o/images%2FD1d5RjEy5oWn7njdqm3CHOsWyuX2%2F20240326-06_28--NtvnaEioFvGY0xtZKbG.png?alt=media&amp;token=9631d046-5489-4a97-a579-78b3aeda03ef</PICTUREURL>
					</PICTURE>
				</PICTURES>
			</POINT>
			<POINT>
				<LAT>39.9813286179124</LAT>
				<LONG>-0.023566351595718214</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>0</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>0</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.9813286179124</DESCLAT>
					<DESCLONG>-0.023566351595718214</DESCLONG>
				</DESCPOINT>
			</POINT>
			<POINT>
				<LAT>39.98178899057892</LAT>
				<LONG>-0.026727765250370586</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>0</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>0</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.98178899057892</DESCLAT>
					<DESCLONG>-0.026727765250370586</DESCLONG>
				</DESCPOINT>
			</POINT>
		</POINTS>
	</POLYGON>
	<POLYGON>
		<NAME>Polygon 1-buffer</NAME>
		<DESCRIPTION/>
		<ISHOLE>0</ISHOLE>
		<BLOCKED>1</BLOCKED>
		<SHAPE>0</SHAPE>
		<NOSURFACE>0</NOSURFACE>
		<SHOWPINS>0</SHOWPINS>
		<SHOWDISTANCES>0</SHOWDISTANCES>
		<LINECOLOR>6</LINECOLOR>
		<LINECUSTOMCOLOR>ff0000</LINECUSTOMCOLOR>
		<LINEWIDTH>2</LINEWIDTH>
		<LINESTYLE>0</LINESTYLE>
		<AREACOLOR>6</AREACOLOR>
		<AREACUSTOMCOLOR>0000ff</AREACUSTOMCOLOR>
		<AREATRANSPARENCY>7</AREATRANSPARENCY>
		<SHOWNAME>1</SHOWNAME>
		<SHOWLABELBACKGROUND>1</SHOWLABELBACKGROUND>
		<SHOWAREAMEASURE>1</SHOWAREAMEASURE>
		<SHOWPERIMETERMEASURE>0</SHOWPERIMETERMEASURE>
		<COORDINATEPOLYGONLABELLATITUDE>39.98233118614747</COORDINATEPOLYGONLABELLATITUDE>
		<COORDINATEPOLYGONLABELLONGITUDE>-0.02577988835655871</COORDINATEPOLYGONLABELLONGITUDE>
		<COORDINATEPERIMETERLABELLATITUDE>39.98233118614747</COORDINATEPERIMETERLABELLATITUDE>
		<COORDINATEPERIMETERLABELLONGITUDE>-0.02577988835655871</COORDINATEPERIMETERLABELLONGITUDE>
		<COORDINATEAREALABELLATITUDE>39.98233118614747</COORDINATEAREALABELLATITUDE>
		<COORDINATEAREALABELLONGITUDE>-0.02577988835655871</COORDINATEAREALABELLONGITUDE>
		<POINTS>
			<POINT>
				<LAT>39.98161197878896</LAT>
				<LONG>-0.026771667506203314</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>1</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>1</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.98161197878896</DESCLAT>
					<DESCLONG>-0.026771667506203314</DESCLONG>
				</DESCPOINT>
			</POINT>
			<POINT>
				<LAT>39.98162251822352</LAT>
				<LONG>-0.02681772695614499</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>1</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>1</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.98162251822352</DESCLAT>
					<DESCLONG>-0.02681772695614499</DESCLONG>
				</DESCPOINT>
			</POINT>
			<POINT>
				<LAT>39.981640014412015</LAT>
				<LONG>-0.02686002700147591</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>1</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>1</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.981640014412015</DESCLAT>
					<DESCLONG>-0.02686002700147591</DESCLONG>
				</DESCPOINT>
			</POINT>
			<POINT>
				<LAT>39.98166373620196</LAT>
				<LONG>-0.02689679996381825</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>1</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>1</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.98166373620196</DESCLAT>
					<DESCLONG>-0.02689679996381825</DESCLONG>
				</DESCPOINT>
			</POINT>
			<POINT>
				<LAT>39.98169269227767</LAT>
				<LONG>-0.026926509131519335</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>1</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>1</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.98169269227767</DESCLAT>
					<DESCLONG>-0.026926509131519335</DESCLONG>
				</DESCPOINT>
			</POINT>
			<POINT>
				<LAT>39.98172567258662</LAT>
				<LONG>-0.026947912977230686</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
					<SHOWLABELBACKGROUND>1</SHOWLABELBACKGROUND>
					<SHOWDESCINREPORT>1</SHOWDESCINREPORT>
					<DESC/>
					<DESCLAT>39.98172567258662</DESCLAT>
					<DESCLONG>-0.026947912977230686</DESCLONG>
				</DESCPOINT>
			</POINT>
			<POINT>
				<LAT>39.98176129890663</LAT>
				<LONG>-0.026960117041006364</LONG>
				<ALT>0</ALT>
				<DESCPOINT>
					<SHOWDESC>0</SHOWDESC>
